add go support to shim + support for forced recompile (refresh)
Signed-off-by: kim (grufwub) <grufwub@gmail.com>

diff --git a/user/bin/shim b/user/bin/shim
--- a/user/bin/shim
+++ b/user/bin/shim
@@ -3,10 +3,12 @@
 # Readonly variables
 readonly USER_DIR="$HOME/.user"
 readonly USER_SCRIPTS_DIR="$USER_DIR/scripts"
+readonly USER_TEMP_DIR="$USER_DIR/temp"
 readonly COMPILED_EXT='out'
 
 # Global variables
 EXEC_PATH=''
+REFRESH=0
 
 #
 # Usage: check_shebang <FILE_NAME> <DEFAULT_EXEC> 
@@ -37,7 +39,30 @@ c_compile() {
   printf "compiling $1...\n"
   gcc "$USER_SCRIPTS_DIR/$1" -o "$2" || return 1
 
-  ! chmod +x "$2" && printf 'failed to make $2 executable\n' && return 1
+  ! chmod +x "$2" && printf "failed to make $2 executable\n" && return 1
+  return 0
+}
+
+#
+# Usage: go_compile <FILE_NAME_NOEXT> <FILE_NAME> <OUTPUT_NAME>
+#
+# Compiles USER_SCRIPTS_DIR/FILE_NAME to USER_SCRIPTS_DIR/OUTPUT_NAME
+# and makes executable, return 1 at any fails
+go_compile() {
+  if ( ! which go > /dev/null 2>&1 ); then
+    printf "go not installed...\n"
+    return 1
+  fi
+
+  printf "copying to temporary directory and compiling $2...\n"
+  mkdir -p "$USER_TEMP_DIR/$1" > /dev/null 2>&1                     || return 1
+  cp "$USER_SCRIPTS_DIR/$2" "$USER_TEMP_DIR/$1/$2" > /dev/null 2>&1 || return 1
+  cd "$USER_TEMP_DIR/$1" > /dev/null 2>&1
+  go build -o "$3"
+  cd - > /dev/null 2>&1
+  rm -rf "$USER_TEMP_DIR/$1" > /dev/null 2>&1 || printf 'failed to clean up go build directory\n'
+
+  ! chmod +x "$3" && printf "failed to make $2 executable\n" && return 1
   return 0
 }
 
@@ -56,7 +81,8 @@ handle_filename() {
 
   path="$USER_SCRIPTS_DIR/$name"
   if [ "$file_ext" = 'c' ]; then
-    path="$path.$COMPILED_EXT"
+    path="$path.$COMPILED_EXT.$file_ext"
+    [ $REFRESH -eq 1 ] && rm "$path"
     [ ! -f "$path" ] && ! c_compile "$1" "$path" && return 1
   elif [ "$file_ext" = 'py' ]; then
     path="$path.$file_ext"
@@ -66,6 +92,10 @@ handle_filename() {
     path="$path.$file_ext"
     name=$(check_shebang "$1" 'sh')
     path="$name $path"
+  elif [ "$file_ext" = 'go' ]; then
+    path="$path.$COMPILED_EXT.$file_ext"
+    [ $REFRESH -eq 1 ] && rm "$path"
+    [ ! -f "$path" ] && ! go_compile "$name" "$1" "$path" && return 1
   else
     printf "incompatible file extension: '.$file_ext'\n"
     return 1
@@ -84,9 +114,16 @@ handle_filename() {
 main() {
   local filename exec_path
 
-  if [ ! -d "$USER_SCRIPTS_DIR" ]; then
-    printf "$USER_SCRIPTS_DIR does not exist\n"
+  if [ ! -d "$USER_SCRIPTS_DIR" ] && ( ! mkdir -p "$USER_SCRIPTS_DIR" > /dev/null 2>&1 ); then
+    printf "$USER_SCRIPTS_DIR does not exist and unable to create!\n"
     return 1
+  fi
+
+  [ ! -d "$USER_TEMP_DIR" ] && mkdir -p "$USER_TEMP_DIR"
+
+  if [ "$1" = '--refresh' ]; then
+    REFRESH=1
+    shift 1
   fi
 
   filename=$(ls "$USER_SCRIPTS_DIR" | grep -e "^$1" | grep -v -E "\.$COMPILED_EXT$" | head -n 1)
